version: '3.9'

services:
  frontend:
    build:
      context: ./healthy-food-tracker
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./drfsite
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app  # Том для сохранения db.sqlite3
    environment:
      - PYTHONUNBUFFERED=1

  dash:
    build:
      context: ./Dash
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./dash:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend

volumes:
  sqlite_data: